mp:
  messaging:
    incoming:
      f1-live-raw:
        connector: smallrye-kafka
        value:
          deserializer: org.apache.kafka.common.serialization.StringDeserializer
      words-in:
        "auto.offset.reset": earliest
        value:
          deserializer: org.apache.kafka.common.serialization.StringDeserializer
    outgoing:
      words-out:
        topic: words
        value:
          serializer: org.apache.kafka.common.serialization.StringSerializer


kafka:
  bootstrap.servers: kafka-main-kafka-bootstrap:9092

quarkus:
  log:
    level: INFO

  jib:
    base-jvm-image: eclipse-temurin:25-jre-noble
