mp:
  messaging:
    incoming:
      f1-live-raw-storage:
        topic: test-f1-live-raw   #test specific
        group:
          id: f1-livetiming-processor-storage
        connector: smallrye-kafka
        #"auto.offset.reset": earliest
        value:
          deserializer: org.apache.kafka.common.serialization.StringDeserializer
      f1-live-raw-in:
        topic: test-f1-live-raw   #test specific
        group:
          id: f1-livetiming-processor-router
        connector: smallrye-kafka
        #"auto.offset.reset": earliest
        value:
          deserializer: org.apache.kafka.common.serialization.StringDeserializer
    outgoing:
      livetiming-out:
        topic: test-f1-live-processed
        connector: smallrye-kafka
        value:
          serializer: org.apache.kafka.common.serialization.StringSerializer
#      session-status-update: #This is an internal in-memory channel
#        broadcast: true

smallrye:
  messaging:
    observation:
      enabled: true

quarkus:
  log:
    level: INFO
  package:
    jar:
      aot:
        enabled: true
  jib:
    base-jvm-image: gcr.io/distroless/java25-debian13
  datasource:
      db-kind: postgresql
      #username: <your username>
      #password: <your password>
      #jdbc:
        #url: jdbc:postgresql://localhost:5432/hibernate_orm_test
        #max-size: 16

app:
  database: app
  livetiming:
    table: live_timing_messages
  session-info:
    table: live_session_info

  log:
    source: "Default config file."

"%prod":
  kafka:
    bootstrap:
      servers: kafka-main-kafka-bootstrap:9092

"%test":
  quarkus:
    devservices:
      enabled: true