apiVersion: apps/v1
kind: Deployment
metadata:
  name: f1-api
  labels:
    app: f1-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: f1-api
  template:
    metadata:
      labels:
        app: f1-api
    spec:
      containers:
        - name: f1-api
          image: local/f1-api
          ports:
            - containerPort: 8080
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-XX:MaxRAMPercentage=75.0"
            - name: QUARKUS_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: f1-db-app
                  key: username
            - name: QUARKUS_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: f1-db-app
                  key: password

          volumeMounts:
            - mountPath: "/home/jboss/config"                  # The file path used by SmallRye to search for config files.
              name: config                          # Name of the "volume" to mount. Specified below in the volumes section.
              readOnly: true
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
      # Map the config map generated by Kustomize as a file volume
      volumes:
        - name: config                              # Give the volume a name you can reference in the container spec.
          configMap:                                # Specifies that you source the data from a ConfigMap.
            name: f1-live-processor-config                    # The name of the ConfigMap to read from
#     serviceAccountName: extractor-default
