# Custom configuration options should be added to this file. It will be mapped into the
# application pod and made available to the container as /config/config.yaml

# Default config settings for your module
source:
    file: 1
#    db:

target:
  kafka:
    enable: false
    clientId: "f1-livetiming-test-source"
    bootstrapHost: "kafka-main-kafka-bootstrap.kafka:9092"
    topic: "test-f1-live-raw"

# Configuration for metrics.
metrics:
  enable: false

printMessages: true
jobDurationSeconds: 7200 # 2 hours