apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#namespace: default
commonLabels:
  app.kubernetes.io/name: web-ui-svelte

resources:
  - web-ui-svelte.deployment.yaml
  - web-ui-svelte.service.yaml
