name: ci-f1-api
on:
  workflow_dispatch:
  pull_request:
    paths:
      - "f1-api/**"
      
jobs:
  build-signalr-to-kakfka:
    uses: "kjetilh33/utilities/.github/workflows/java-maven-skaffold-build.yml@main"
    with:
      repositoryFolder: "./f1-api/" 
