name: ci-f1-live-processor
on:
  workflow_dispatch:
  pull_request:
    paths:
      - "f1-live-processor/**"
      
jobs:
  build-signalr-to-kakfka:
    uses: "kjetilh33/utilities/.github/workflows/java-maven-skaffold-build.yml@main"
    with:
      repositoryFolder: "./f1-live-processor/" 
