name: package-livetiming-generator
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "livetiming-generator/**"
      
jobs:
  package-livetiming-generator:
    uses: "kjetilh33/utilities/.github/workflows/java-maven-skaffold-build-push-ghcr.yml@main"
    with:
      repositoryFolder: "./livetiming-generator/"
    secrets: inherit
